pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm run build 

  deploy:
    image: docker/compose:1.23.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d 
    volumes:
      - name: docker_sock
        host:
          path: /var/run/docker.sock