pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm run build 

  deploy:
    image: docker/compose
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker-compose up -d
    volume:
      - /var/run/docker.sock:/var/run/docker.sock