pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm run build 

  deploy:
    image: docker/compose
    commands:
      - docker compose up -d
    volume:
      - /var/run/docker.sock:/var/run/docker.sock