pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g serve
      - npm run build 

  deploy:
    image: appleboy/drone-ssh
    host: 159.203.105.174
    port: 22
    username: yamyam
    # volumes:
    #   - /home/yamyam/.ssh/id_rsa:/root/ssh/drone_rsa
    # key_path: /root/ssh/drone_rsa
    secrets:
      - source: DRONE_RSA
        target: ssh_key
      - source: HOST_NAME
        target: ssh_host
    script:
      - pwd
      - ls
      - serve -s build

  # deploy:
  #   image: maoxuner/drone-ssh-deploy
  #   settings:
  #     host: 159.203.105.174
  #     user: yamyam
  #     key:
  #       from_secret: SSH_KEY
  #     deploy_path: /cra-template
  #     PLUGIN_DEPLOY_PATH: /cra-template
  #     source: .
  #     exclude:
  #       - .git
  #       - .gitignore
  #     script:
  #       - pwd
  #       - ls
  #       - serve -s build
  #     debug_mode: false