pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g pm2
      - npm run build 
      - pm2 start cra-template/node_modules/react-scripts/scripts/start.js --name "my-app"

