pipeline:
  # setup:
  #   image: node:latest
  #   commands: 
  #     - npm install
  #     - npm run build 

  build:
    image: docker/compose
    commands:
      - docker-compose build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: docker/compose
    commands:
      - docker-compose up -d --force-recreate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock