pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g serve
      - npm run build 

  deploy:
    image: maoxuner/drone-ssh-deploy
    settings:
      host: 159.203.105.174
      user: yamyam
      key:
        from_secret: ${SSH_KEY}
      deploy_path: /cra-template
      source: .
      exclude:
        - .git
        - .gitignore
      script:
        - pwd
        - ls
        - serve -s build
      debug_mode: false