pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g serve
      - npm run build 

  deploy:
    image: appleboy/drone-scp
    settings:
      host: 159.203.105.174
      port: 22
      user: yamyam
      key:
        from_secret: SSH_KEY
      target: /cra-template
      rm: true
      source: .

  # deploy:
  #   image: maoxuner/drone-ssh-deploy
  #   settings:
  #     host: 159.203.105.174
  #     user: yamyam
  #     key:
  #       from_secret: SSH_KEY
  #     deploy_path: /cra-template
  #     PLUGIN_DEPLOY_PATH: /cra-template
  #     source: .
  #     exclude:
  #       - .git
  #       - .gitignore
  #     script:
  #       - pwd
  #       - ls
  #       - serve -s build
  #     debug_mode: false