pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g serve
      - npm run build 

  deploy:
    image: appleboy/drone-ssh
    group: ssh
    host:
      - 159.203.105.174
    port: 22
    username: yamyam
    command_timeout: 120
    secrets: [ SSH_KEY ]
    script:
      - pwd
      - ls
      - serve -s build
    when:
      branch: master

  # deploy:
  #   image: maoxuner/drone-ssh-deploy
  #   settings:
  #     host: 159.203.105.174
  #     user: yamyam
  #     key:
  #       from_secret: SSH_KEY
  #     deploy_path: /cra-template
  #     PLUGIN_DEPLOY_PATH: /cra-template
  #     source: .
  #     exclude:
  #       - .git
  #       - .gitignore
  #     script:
  #       - pwd
  #       - ls
  #       - serve -s build
  #     debug_mode: false