pipeline:
  # setup:
  #   image: node:latest
  #   commands: 
  #     - npm install
  #     - npm run build 
  build:
    image: docker/compose:1.23.2
    commands:
      - docker-compose build
  deploy:
    image: docker/compose:1.23.2
    commands:
      - docker-compose up -d 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock