pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g pm2
      - npm run build 
  publish-web-docker:
    image: plugins/docker:1.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dockerfile: ./Dockerfile
    context: .
    when:
      branch: ["master"]
      event: [push]
  

