pipeline:
  publish-web-docker:
    image: plugins/docker:1.12
    tags:
      - "${DRONE_BRANCH}_${DRONE_COMMIT}"
    dockerfile: ./Dockerfile
    context: .
    when:
      branch: ["master"]
      event: [push]
  

