pipeline:
  setup:
    image: node:latest
    commands: 
      - npm install
      - npm install -g serve
      - npm run build 

  deploy:
    image: appleboy/drone-ssh
    host: 159.203.105.174
    port: 22
    username: yamyam
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1oQIxh3oTGeem5WTjH7XDdVECladzHtOtVtzpCh62HAKSLYFV8ItMU01sNBRGIUEq/w7C9mL3ZhS9FAcTX9I4ydEvvpPzRI1RN56u9dDf/B7g39JGYD500Ypn+C2nKBLAlYrJUMRFxdmj8ZCjfti/5zzWScYUAYbovjImnJnCOh2JSa1MkC7W8v5CMedpPYr5AV3pVRmGnJ+tj4cBieYi8EWkcX0BHvueYRiJQ6QgKMOABLKdRCqW2+xI1HxAEcb2N8hRQWpAKRyA9zFmm/aRlry3g483zpUEkzQwo2RITvsGtj7ThzY1fLScdpvy0TbDPoyaU21DwApe3wyxxXDx meriampales@cpe-172-118-19-115.socal.res.rr.com
    script:
      - pwd
      - ls
      - serve -s build

  # deploy:
  #   image: maoxuner/drone-ssh-deploy
  #   settings:
  #     host: 159.203.105.174
  #     user: yamyam
  #     key:
  #       from_secret: SSH_KEY
  #     deploy_path: /cra-template
  #     PLUGIN_DEPLOY_PATH: /cra-template
  #     source: .
  #     exclude:
  #       - .git
  #       - .gitignore
  #     script:
  #       - pwd
  #       - ls
  #       - serve -s build
  #     debug_mode: false