pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: 159.203.105.174
    port: 22
    username: yamyam
    volumes:
      - /home/yamyam/.ssh/id_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    script:
      - cd cra-template
      - pwd
      - git pull origin master
      - npm run build
      - pm2 start pm2-app.json

services:
  database:
    image: mysql
    environment:
      - DATABASE_URL=mysql://mysql@localhost