version: '3.2'

services:
  webserver:
    build: .
    tty: true
    ports:
      - "8082:8082"
    # command: ["sh","-c","pm2-runtime start pm2-app.json"]
    volumes:
      - ./:/app
      - /app
    