version: '3.2'

services:
  webserver:
    build: .
    container_name: node_cra
    tty: true
    ports:
      - "8082:8082"
    command: ["sh","-c", "pm2 start node_modules/react-scripts/scripts/start.js --name "my-app""]
