version: '3.2'

services:
  webserver:
    build: .
    container_name: node_cra
    tty: true
    ports:
      - "8082:8082"
    command: ["sh","-c","pm2-runtime start /app/cra-template/pm2-app.json"]
    volumes:
      - ./:/app/:cached
      - /app/cra-template/node_modules
