version: '3.2'

services:
  webserver:
    build: .
    tty: true
    ports:
      - "8082:8082"
    # command: ["sh","-c","pm2-runtime start pm2-app.json"]
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public/:/app/public
      - ./src/:/app/src
      - ./package.json:/app/package.json
      - ./pm2-app.json:/app/package.json
    