version: '3.2'

services:
  webserver:
    build: .
    tty: true
    ports:
      - "8082:8082"
    # command: ["sh","-c","pm2-runtime start /app/pm2-app.json"]
    volumes:
      - ./:/app
      - /app/node_modules
      - public:/app/public
      - src:/app/src
      - pm2-app.json:/app/pm2-app.json
      - package.json:/app/package.json
    